// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { listLocalDatabases } from "@prisma/adapter-d1";
import { defineConfig } from "prisma/config";

const dbFile = (() => {
    try {
        return listLocalDatabases().pop() ?? "db.sqlite";
    }
    catch {
        return "db.sqlite";
    }
})();

export default defineConfig({
    schema: "prisma/schema",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        url: `file:${dbFile}`,
    },
});
