/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardLinksIndexRouteImport } from './routes/dashboard/links/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardLinksShortIdIndexRouteImport } from './routes/dashboard/links/$shortId/index'
import { Route as DashboardLinksShortIdAnalyticsRouteImport } from './routes/dashboard/links/$shortId/analytics'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinksIndexRoute = DashboardLinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLinksShortIdIndexRoute =
  DashboardLinksShortIdIndexRouteImport.update({
    id: '/links/$shortId/',
    path: '/links/$shortId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLinksShortIdAnalyticsRoute =
  DashboardLinksShortIdAnalyticsRouteImport.update({
    id: '/links/$shortId/analytics',
    path: '/links/$shortId/analytics',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/links/': typeof DashboardLinksIndexRoute
  '/dashboard/links/$shortId/analytics': typeof DashboardLinksShortIdAnalyticsRoute
  '/dashboard/links/$shortId/': typeof DashboardLinksShortIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/links': typeof DashboardLinksIndexRoute
  '/dashboard/links/$shortId/analytics': typeof DashboardLinksShortIdAnalyticsRoute
  '/dashboard/links/$shortId': typeof DashboardLinksShortIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/links/': typeof DashboardLinksIndexRoute
  '/dashboard/links/$shortId/analytics': typeof DashboardLinksShortIdAnalyticsRoute
  '/dashboard/links/$shortId/': typeof DashboardLinksShortIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/links/'
    | '/dashboard/links/$shortId/analytics'
    | '/dashboard/links/$shortId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/links'
    | '/dashboard/links/$shortId/analytics'
    | '/dashboard/links/$shortId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/links/'
    | '/dashboard/links/$shortId/analytics'
    | '/dashboard/links/$shortId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/links/': {
      id: '/dashboard/links/'
      path: '/links'
      fullPath: '/dashboard/links/'
      preLoaderRoute: typeof DashboardLinksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/links/$shortId/': {
      id: '/dashboard/links/$shortId/'
      path: '/links/$shortId'
      fullPath: '/dashboard/links/$shortId/'
      preLoaderRoute: typeof DashboardLinksShortIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/links/$shortId/analytics': {
      id: '/dashboard/links/$shortId/analytics'
      path: '/links/$shortId/analytics'
      fullPath: '/dashboard/links/$shortId/analytics'
      preLoaderRoute: typeof DashboardLinksShortIdAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLinksIndexRoute: typeof DashboardLinksIndexRoute
  DashboardLinksShortIdAnalyticsRoute: typeof DashboardLinksShortIdAnalyticsRoute
  DashboardLinksShortIdIndexRoute: typeof DashboardLinksShortIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLinksIndexRoute: DashboardLinksIndexRoute,
  DashboardLinksShortIdAnalyticsRoute: DashboardLinksShortIdAnalyticsRoute,
  DashboardLinksShortIdIndexRoute: DashboardLinksShortIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
