/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortIdRouteImport } from './routes/$shortId'
import { Route as IndexRouteImport } from './routes/index'

const ShortIdRoute = ShortIdRouteImport.update({
  id: '/$shortId',
  path: '/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shortId': typeof ShortIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shortId': typeof ShortIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$shortId': typeof ShortIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$shortId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$shortId'
  id: '__root__' | '/' | '/$shortId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortIdRoute: typeof ShortIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/$shortId': {
      id: '/$shortId'
      path: '/$shortId'
      fullPath: '/$shortId'
      preLoaderRoute: typeof ShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortIdRoute: ShortIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
